version: '3.4'

services:
  sensecapitaltesttask:
    image: ${DOCKER_REGISTRY-}sensecapitaltesttask
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: SenseCapitalTestTask/Dockerfile

  sensecapitaltesttask.db:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: tick_crossdb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  sensecapitaltesttask.admin:
    image: mongo-express
    container_name: mongodb_admin
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@sensecapitaltesttask.db:27017/
